### PR TITLE
Multiple route warnings

### LINKED ISSUE #697: Ensure hops are selected on all selected routes of an adjust-speed modification
An MIT user reports:

> When I selected all routes, they did appear in the list of routes in the modification JSON, but they did not visualize and drawing polygons always resulted in an empty array for hops. So I ended up selecting the routes one by one. 

This, along with #696, makes me wonder whether hops are correctly being selected for all routes in an adjust-speed modification, or just the first.

### PR DESCRIPTION
**Pull request by trevorgerhardt**
## Description

When multiple routes are selected, disallow selecting portions of the route displayed as the modification will be applied to the entirety of each route. This also updates the warning messages shown to reflect that.

Fixes #697 

## How to test
1. Create Adjust Speed modification.
2. Select all routes.
3. Run analysis ensuring the modification was applied for each route in the feed.
4. Repeat for Remove Trips.

### CODE REVIEW

**Comment by abyrd** [comment]
Above, I tested with only adjust-speed. I'm now testing with remove-trips. When I create a new remove-trips modification then try to edit it, upon going to URL https://analysis-staging-git-multiple-route-warnings.conveyal.now.sh/regions/5d6ccad032b98e3060748c0c/projects/5d6cdd6332b98e3060748c13/modifications/5d77280c32b98e3060748cc7 I get a blank screen. Console shows this error:

```
[Error] TypeError: null is not an object (evaluating 't.map') — [modificationId].js:0
	(anonymous function) (_app.js:1:60268)
	value (_app.js:1:24572)
	callback (commons.93450e802815e755e26f.js:1:627226)
	oa (commons.93450e802815e755e26f.js:1:619603)
	ra (commons.93450e802815e755e26f.js:1:619402)
	Va (commons.93450e802815e755e26f.js:1:629418)
	Za (commons.93450e802815e755e26f.js:1:631893)
	(anonymous function) (commons.93450e802815e755e26f.js:1:645122)
	unstable_runWithPriority (commons.93450e802815e755e26f.js:1:4004)
	As (commons.93450e802815e755e26f.js:1:645079)
	Ps (commons.93450e802815e755e26f.js:1:644833)
	Cs (commons.93450e802815e755e26f.js:1:644178)
	Os (commons.93450e802815e755e26f.js:1:643199)
	$a (commons.93450e802815e755e26f.js:1:642073)
	ui (commons.93450e802815e755e26f.js:1:602706)
	ui
	(anonymous function)
	promiseReactionJob
```

**Comment by trevorgerhardt** [comment]
@abyrd I agree! I separated out the map display warning from the modification application warning 
but you may not have seen it (see here: https://github.com/conveyal/analysis-ui/pull/917/files#diff-2de8afe03c6f2c3748b1fbc15044d744R76-R77).

Screen Shot 2019-09-10 at 12 38 09 PM

**Comment by abyrd** [comment]
That warning is displayed when all routes are selected. I mean a similar warning would apply when 2+ routes are selected.

**Comment by trevorgerhardt** [comment]
@abyrd Ah, and my change was supposed to prevent that. Forgot the `lodash/get` lets `null`s through. Just pushed a change that should fix that 👍

**Comment by abyrd** [comment]
Everything seems to work. I do still think eventually we should show the message when any number of routes > 1 is selected, not just when all routes are selected.

**Pull request merged**
