### PR TITLE
Remove internal authenticated fetch

### PR DESCRIPTION
**Pull request by trevorgerhardt**
Anytime authenticated fetch is used manually we are unable to map it easily to state to show loading indicators or status messages. This PR is going to move all uses of fetch to use the woonerf/fetch action pattern. 

Note: This does not include edits to `utils/browsochrones.js`. That requires a lot of unpacking and will come in a subsequent pull request.

### CODE REVIEW

**Comment by mattwigway** [comment]
Bundle upload does not work with these changes:

image

Grid upload is broken as well, but there are no informative error messages.

Also, please rebase; some issues that are fixed in dev regarding the switch to d3-color are still present here.

**Comment by trevorgerhardt** [comment]
@mattwigway fixes have been made, please check again when you have a minute!

**Comment by mattwigway** [comment]
Bundle upload appears to still not be working. I no longer see an error, but it remains spinning "processing" even once the polled bundle status is DONE.

**Comment by mattwigway** [comment]
Grid upload works though!

**Comment by trevorgerhardt** [comment]
@mattwigway regarding changes to `utils/segments`... my comments yesterday about merging/rebasing were referring to this PR in that it caused an unusual replay of commits to occur. I think everything is fine, it just appears like I changed more in this PR than I actually have.

**Comment by trevorgerhardt** [comment]
Good catch on the bundle upload, it was a simple fix: had checked "state" instead of "status". That's what these reviews are for! 👌

**Comment by mattwigway** [comment]
Works now, thanks @trevorgerhardt!

**Pull request merged**
