### PR TITLE
Run Analysis Backend for automating Cypress Tests

### PR DESCRIPTION
**Pull request by trevorgerhardt**
The integration workflow now sets up a local backend server to run for each pull request.

These are running the local version of the Cypress tests only.

### CODE REVIEW

**Comment by Nate-Wessel** [comment]
Looking at the logs, it appears three Cypress tests actually failed. 
https://github.com/conveyal/analysis-ui/pull/1119/checks?check_run_id=788129189#step:9:2812

**Comment by trevorgerhardt** [comment]
> Looking at the logs, it appears three Cypress tests actually failed.
> https://github.com/conveyal/analysis-ui/pull/1119/checks?check_run_id=788129189#step:9:2812

Not entirely sure what's happening there. Seems to be inconsistent behavior.

**Comment by trevorgerhardt** [comment]
@Nate-Wessel all passing now. But I removed part of the region test that compared the map bounds. It wasn't consistently passing, especially during CI.

**Comment by Nate-Wessel** [comment]
> @Nate-Wessel all passing now. But I removed part of the region test that compared the map bounds. It wasn't consistently passing, especially during CI.

That part depends mostly on whatever external API is behind the location search bar. It's always worked on my machine though, so I wonder if the instance running in CI has a working internet connection?

**Comment by trevorgerhardt** [comment]
> That part depends mostly on whatever external API is behind the location search bar. It's always worked on my machine though, so I wonder if the instance running in CI has a working internet connection?

The tests using location search are working now. It's the test that does the `map.getBounds().contains...` that passes/fails inconsistently.

**Comment by trevorgerhardt** [comment]
@Nate-Wessel looks like Cypress solved the issue already: https://github.com/cypress-io/github-action/issues/168

**Pull request merged**
