### PR TITLE
Pass the error value to lockUiWithError

### PR DESCRIPTION
**Pull request by trevorgerhardt**
Which is parsed via woonerf

addresses #300

@mattwigway is there a specific example you had that I can test to make sure it works for your case?

### CODE REVIEW

**Comment by mattwigway** [comment]
@trevorgerhardt I'm still seeing the same blank error box.

The way I make it happen reliably is to add the line `halt(400);` on line 33 of SinglePointAnalysisController in the analyst project, which makes the backend always crash.

**Comment by trevorgerhardt** [comment]
@mattwigway this should fix other error messages so we should move the "Display error by manually adding halt" to another task.

**Comment by mattwigway** [comment]
@trevorgerhardt I don't fully understand. #300 was fixed by https://github.com/conveyal/analysis-ui/pull/312 ; what value add does this provide?

**Comment by trevorgerhardt** [comment]
Ah! 👍

**Comment by mattwigway** [comment]
hmm, some errors are showing the blank error box again, specifically if the backend crashes when editing a project. I'm wondering if we need this change after all.

**Pull request closed without merging**
