### PR TITLE
Pull out common code between Add Trips & Reroute.

### PR DESCRIPTION
**Pull request by trevorgerhardt**
The form and functionality required to begin editing the alignments of Add Trips & Reroute modifications is almost identical and therefore an appropriate place to pull out into a common component.

### CODE REVIEW

**Comment by trevorgerhardt** [comment]
@mattwigway looks like I messed up the defaults. I believe it is working correctly now, please take a look to verify the behavior!

**Comment by mattwigway** [comment]
Not quite. When I edit an add-trip-pattern modification, the checkbox now reflects the behavior correctly, but defaults to extending from the beginning. We should default to extending from the end. Also, when I edit a reroute that has only a from stop, it extends from the beginning rather than the end.

**Comment by trevorgerhardt** [comment]
@mattwigway so the logic all works the same on my end. This latest change makes it more obvious where we're getting the `extendFromEnd` boolean from since it's different for reroute and add trip patterns.

Please test again!

**Comment by mattwigway** [comment]
Great! I'll take a look before I take off today, unless you were looking for a quick test right away.

**Comment by mattwigway** [comment]
It's working locally now.  Weird 🌔 .

**Comment by abyrd** [comment]
Actually the moon phase is more like 🌒 .

**Pull request merged**
