### PR TITLE
Flow coverage improvements

### PR DESCRIPTION
**Pull request by trevorgerhardt**
Opening this PR for @evansiroky so that we can merge it in ASAP and not let it get too out of date and cause conflicts.

### CODE REVIEW

**Comment by trevorgerhardt** [comment]
Hmmmm that's a lot of failing tests...

**Comment by trevorgerhardt** [comment]
I'll try to get to it, but it might be punted for other priorities. Hope it doesn't become too out of date in the mean time.

**Comment by evansiroky** [comment]
This PR now has flow typings for all tests in the following directories:

- lib/__tests__
- lib/actions/**/__tests__
- lib/components/**/__tests__

**Comment by trevorgerhardt** [comment]
Since I opened this I can't approve it but it has my approval so let's merge 👍

**Pull request merged**
