### PR TITLE
Misc fixes

### PR DESCRIPTION
**Pull request by mattwigway**

### CODE REVIEW

**Comment by mattwigway** [comment]
I will rebase.

**Comment by trevorgerhardt** [comment]
@mattwigway looks like you just need to fix that one snapshot. Are there other conflicts that github isn't picking up?

**Comment by trevorgerhardt** [comment]
@mattwigway did the changes needed make it back into dev? This PR is getting increasingly out of date

**Comment by mattwigway** [comment]
Nope, once authenticated fetch changes are merged I'm going to bring this
stuff over by hand.

**Comment by trevorgerhardt** [comment]
@mattwigway it's too early to be online, go back to bed 😉

**Comment by trevorgerhardt** [comment]
Authenticated fetch changes have been merged 👍

**Comment by trevorgerhardt** [comment]
Oh, you're traveling to Boston today! No rush on this then

**Comment by trevorgerhardt** [comment]
@mattwigway what's the status of this PR? Is there code here that needs to be merged still?

**Comment by mattwigway** [comment]
Yes. The main things to bring over are:

* Status updates during upload of grids and gtfs feeds
* Always using messages rather than the raw types when displaying modification types
* Histogram disappearing at 120 minutes

I should be able to tackle this tomorrow or Monday.

**Pull request closed without merging**
