### PR TITLE
Upgrade to React v16

### LINKED ISSUE #559: Update to Mastarm 4.0
Mastarm 4.0 uses Node8 and the latest versions of our build, linting, and type checking libraries. We should upgrade as soon as we can. This will cause ESLint & Flow to show a lot more errors that will need to be fixed. Will probably also want to update React v16 in this same pass as we'll be refactoring a lot of related code.

### LINKED ISSUE #764: Use React/Flow SyntheticEvent<T>s instead generic Events
The `Event & {target: HTMLInputElement}` style was gives more flow errors and in my research I found that we should've been using SyntheticEvent<?>'s anyway. I'm not 100% sure that I'm doing it correctly, but it's more "appropriate" than before. See Flow docs for more info: https://flow.org/en/docs/react/events/

### LINKED ISSUE #778: Remove all usage of PropTypes internally
Mainly used in the Report components

### PR DESCRIPTION
**Pull request by trevorgerhardt**
Updates React to v16 and necessary libraries to be compatible with it. Significant libraries upgraded:

- Mastarm to v5
- Node to v10
- Enzyme & Jest -- most snapshots needed to be updated
- Redux to v6

closes #559 
closes #778 
closes #764 (well, makes it irrelevant)

### CODE REVIEW

**Comment by evansiroky** [comment]
large task is an appropriate label for this!

**Comment by evansiroky** [comment]
What were the main reasons for removing flow typing?

**Comment by trevorgerhardt** [comment]
1699 errors of various kinds. Attached: 
[flow-errors.txt](https://github.com/conveyal/analysis-ui/files/3056722/flow-errors.txt)

**Comment by trevorgerhardt** [comment]
For the record I think we should consider the discussion of using flow for this project over and move on. While typing is helpful, the ecosystem has overall been moving on to TypeScript and any additional flow specific code is going to be removed at some point.

**Comment by trevorgerhardt** [comment]
eslint + Jest should be able to handle our testing needs in the interim.

**Comment by trevorgerhardt** [comment]
@ansoncfit this should now pass the katalon tests completely. It has also been up on staging for a week. I would like to merge soon if possible. Let me know your thoughts.

**Comment by ansoncfit** [comment]
Still curious about the extra-wide modals, but otherwise this looks good for merging.

**Pull request merged**
